insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('mwylam0@dailymail.co.uk', 'Michaelina', 'Wylam', 'Kunstakademie Düsseldorf.', 1);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('tsaladino1@wsj.com', 'Tallou', 'Saladino', 'Belarusian-Russian University', 2);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('odurman2@webs.com', 'Olympe', 'Durman', 'Shanxi Normal University', 3);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('nleadbitter3@zdnet.com', 'Nevins', 'Leadbitter', 'National Academy of Fine Arts', 4);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('jmillery4@360.cn', 'Justen', 'Millery', 'Universidad de Managua (U de M)', 5);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('hlefeuvre5@feedburner.com', 'Herb', 'Le feuvre', 'New Jersey City University', 6);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('tboddice6@accuweather.com', 'Tory', 'Boddice', 'Kenyatta University', 7);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('rhennemann7@buzzfeed.com', 'Ros', 'Hennemann', 'Fachhochschule Ravensburg-Weingarten', 8);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('pdugall8@sourceforge.net', 'Paige', 'Dugall', 'National Yang Ming Medical College', 9);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('gtrude9@dropbox.com', 'Garland', 'Trude', 'Water Resources University', 10);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('tvanneta@oaic.gov.au', 'Terry', 'Vannet', 'Ritsumeikan University', 11);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('npetrenkob@histats.com', 'Niko', 'Petrenko', 'Technological University (Pyay)', 12);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('mhoppnerc@youku.com', 'Marcellus', 'Hoppner', 'University of the Visayas', 13);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('cmacallesterd@quantcast.com', 'Codie', 'MacAllester', 'University of Iowa', 14);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('yseekse@dell.com', 'Yul', 'Seeks', 'West Pomeranian Business School in Szczecin', 15);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('bpoelf@amazon.co.jp', 'Beryle', 'Poel', 'Universidade Federal de Campina Grande', 16);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('akempsterg@instagram.com', 'Avril', 'Kempster', 'Gokhale Institute of Politics and Economics', 17);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('bferrareseh@csmonitor.com', 'Berkeley', 'Ferrarese', 'National University of Modern Languages', 18);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('cfidelli@macromedia.com', 'Carver', 'Fidell', 'Islamic Azad University, Janah', 19);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('ahirschmannj@earthlink.net', 'Avigdor', 'Hirschmann', 'Universidad Autónoma de Nuevo León', 20);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('jsettlek@patch.com', 'Jesus', 'Settle', 'Technological University of Podillya', 21);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('jgalleyl@google.com.au', 'Jenna', 'Galley', 'Bowie State University', 22);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('tmaccarterm@tripod.com', 'Tibold', 'MacCarter', 'University of New Brunswick', 23);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('dbassindalen@google.com.au', 'Darbie', 'Bassindale', 'St. Petersburg Institute of Arts and Restoration', 24);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('hmcgaraghano@pcworld.com', 'Hortense', 'McGaraghan', 'Pes University', 25);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('cloaldayp@constantcontact.com', 'Christal', 'Loalday', 'University Tun Abdul Razak', 26);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('lstricklandq@amazon.co.jp', 'Libbie', 'Strickland', 'Academy of Fine Arts and Design in Bratislava', 27);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('tboundeyr@google.pl', 'Tabatha', 'Boundey', 'Institute of Commerce and Business', 28);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('mcrebers@forbes.com', 'Morna', 'Creber', 'University of Witwatersrand', 29);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('dcasonet@uol.com.br', 'Datha', 'Casone', 'Athens School of Fine Arts', 30);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('pcalderau@statcounter.com', 'Patrice', 'Caldera', 'Afyon Kocatepe University', 31);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('hpundyv@rakuten.co.jp', 'Hartwell', 'Pundy', 'Rochester Institute of Technology', 32);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('ssenechaultw@vimeo.com', 'Shurlocke', 'Senechault', 'Universidad de Piura', 33);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('vmccorkellx@eventbrite.com', 'Veronica', 'McCorkell', 'University of Strathclyde', 34);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('mdennanty@free.fr', 'Manolo', 'Dennant', 'Al-Imam Mohamed Ibn Saud Islamic University', 35);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('haleninz@reference.com', 'Harland', 'Alenin', 'Freie Kunst-Studienstätte Ottersberg', 36);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('sbromage10@chron.com', 'Shandra', 'Bromage', 'St. Francis Medical Center College of Nursing', 37);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('dbestall11@adobe.com', 'Domeniga', 'Bestall', 'Birsk State Pedagogical Institute', 38);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('bbilling12@scribd.com', 'Bartholomew', 'Billing', 'University of Trieste', 39);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('cmartijn13@google.ru', 'Chickie', 'Martijn', 'Kwara State Polytecnic', 40);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('lmcauslan14@joomla.org', 'Loni', 'McAuslan', 'Technische Universität Chemnitz', 41);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('dmcavin15@hhs.gov', 'Dodie', 'McAvin', 'University of the District of Columbia', 42);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('gburdge16@themeforest.net', 'Gorden', 'Burdge', 'Ternopil Academy of National Economy', 43);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('ltompion17@pinterest.com', 'Linzy', 'Tompion', 'Florida International University', 44);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('cpinnijar18@umich.edu', 'Chane', 'Pinnijar', 'Ecole Nationale Supérieure d''Ingénieurs en Mécanique et Energétique de Valenciennes', 45);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('rpedroni19@github.io', 'Ronald', 'Pedroni', 'National University of Shipbuilding', 46);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('jgulberg1a@so-net.ne.jp', 'Jinny', 'Gulberg', 'Eritrea Institute of Technology', 47);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('lmoral1b@ask.com', 'Lorain', 'Moral', 'Universität für künstlerische und industrielle Gestaltung Linz', 48);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('wbramo1c@exblog.jp', 'Winston', 'Bramo', 'Zachodniopomorska School of Science and Engineering', 49);
insert into ALUMNE (EMAIL, NOM, COGNOMS, GRUP, GRUP_ID) values ('rtobias1d@sogou.com', 'Ronni', 'Tobias', 'Khalifa University', 50);
